//! End-to-end pipeline test against synthetic Park-style TIFFs in
//! /tmp/pv_testdata and /tmp/pv_incomplete (generated by the dev harness).
//! Skips silently if the fixtures are absent (CI generates its own).

use parkviewer::backgrounds::{self, BgMethod, BgParams};
use parkviewer::colormaps::{data_to_rgb, Colormap};
use parkviewer::core;
use std::path::Path;

fn have(dir: &str) -> bool {
    Path::new(dir).exists()
}

#[test]
fn end_to_end_scan_parse_render() {
    if !have("/tmp/pv_testdata") {
        eprintln!("test corpus missing — skipping");
        return;
    }
    let files = core::get_tiff_files(Path::new("/tmp/pv_testdata"));
    assert_eq!(files.len(), 8, "should find 8 tiffs");

    // filename parsing
    let fwd = files
        .iter()
        .find(|f| f.channel.as_deref() == Some("Z Height") && f.direction.as_deref() == Some("Forward"))
        .expect("Z Height Forward");
    assert_eq!(fwd.experiment, "efm"); // matches python: split('_')[0]
    assert_eq!(fwd.frame, Some(7));

    // metadata extraction from the Park binary tag
    let meta = fwd.tiff_meta.as_ref().expect("tiff meta parsed");
    assert_eq!(
        meta.channel.as_deref(),
        Some("Z Height"),
        "UTF-16-LE channel from tag 50435"
    );
    let sz = meta.scan_size_um.expect("scan size");
    assert!((sz - 12.5).abs() < 1e-6, "scan size {sz}");
    let rate = meta.scan_rate_hz.expect("scan rate");
    assert!((rate - 1.1).abs() < 1e-6);
    let zs = meta.z_scale.expect("z scale");
    assert!((zs - 3.5).abs() < 1e-6);
    assert_eq!(meta.software.as_deref(), Some("Park Systems SmartScan 2.0"));

    // load + background subtract + render
    let (w, h, raw) = {
        let (a, b) = core::tiff_dimensions(&fwd.path).unwrap();
        (a as usize, b as usize, core::load_tiff_f32(&fwd.path).unwrap())
    };
    assert_eq!((w, h), (256, 256));
    let mut data = raw.clone();
    backgrounds::apply(&mut data, w, h, BgMethod::LineMean, &BgParams::default());
    // after row-mean subtraction, each row mean ≈ 0
    let row0_mean: f32 = data[0..w].iter().sum::<f32>() / w as f32;
    assert!(row0_mean.abs() < 1e-2, "row mean after LineMean: {row0_mean}");

    let (vmin, vmax) = (
        backgrounds::nanpercentile(&data, 1.0),
        backgrounds::nanpercentile(&data, 99.0),
    );
    eprintln!("vmin={vmin} vmax={vmax} data[0..4]={:?}", &data[0..4.min(data.len())]);
    assert!(vmin <= vmax, "vmin={vmin} vmax={vmax}");
    let cmap = Colormap::get(core::colormap_for_channel(Some("Z Height")));
    assert_eq!(cmap.name, "terrain");
    let rgb = data_to_rgb(&data, w, h, &cmap, vmin, vmax);
    assert_eq!(rgb.len(), w * h * 3);
    // pixels are not all identical
    assert!(rgb.windows(3).any(|w| w[0] != w[1] || w[1] != w[2]));
}

#[test]
fn incomplete_detection() {
    if !have("/tmp/pv_incomplete") {
        eprintln!("test corpus missing — skipping");
        return;
    }
    let files = core::get_tiff_files(Path::new("/tmp/pv_incomplete"));
    assert_eq!(files.len(), 1);
    let f = &files[0];
    let (w, h) = core::tiff_dimensions(&f.path).unwrap();
    let data = core::load_tiff_f32(&f.path).unwrap();
    let (complete, pct) = core::check_image_complete(&data, w as usize, h as usize, 0.1);
    assert!(!complete, "should detect truncation");
    // 27 flat rows of 256 → ~89.5%
    assert!((89.0..90.5).contains(&pct), "pct={pct}");
}

#[test]
fn filters_and_frames() {
    if !have("/tmp/pv_testdata") {
        eprintln!("test corpus missing — skipping");
        return;
    }
    let files = core::get_tiff_files(Path::new("/tmp/pv_testdata"));
    let (ch, dir, exp) = core::get_unique_values(&files);
    assert_eq!(ch.len(), 4);
    assert_eq!(dir.len(), 2);
    assert!(exp.len() >= 1);

    // channel filter keeps only EFM*
    let efm_channels = vec!["EFM Phase".to_string(), "EFM Amplitude".to_string()];
    let efm_files = core::filter_files(&files, Some(&efm_channels), None, None);
    assert_eq!(efm_files.len(), 4);
    for f in &efm_files {
        let c = f.channel.as_deref().unwrap();
        assert!(c == "EFM Phase" || c == "EFM Amplitude");
    }

    // frames: one (experiment, frame) pair
    let frames = core::get_frames_info(&files);
    assert_eq!(frames.len(), 1);

    // channels for that frame, sorted by channel name
    let (e, f) = frames[0].clone();
    let chans = core::get_all_channels_for_frame(&files, &e, f, None);
    assert_eq!(chans.len(), 8);
    let names: Vec<&str> = chans
        .iter()
        .map(|c| c.channel.as_deref().unwrap())
        .collect();
    let mut sorted_names = names.clone();
    sorted_names.sort();
    assert_eq!(names, sorted_names, "channels sorted by name");
}

fn efm_only(files: &[core::ParkFileMeta]) -> Vec<String> {
    files
        .iter()
        .filter(|f| f.channel.as_deref().map_or(false, |c| c.starts_with("EFM")))
        .filter_map(|f| f.channel.clone())
        .collect()
}
fn efm_only_files(files: &[core::ParkFileMeta]) -> Vec<String> {
    efm_only(files)
}